/* Parallel structure-aware prover: root-split DFS across CPU threads.
 *
 * Phase 1 (single thread): DFS to arc-depth DEPTH, collecting live nodes
 *   as tasks (mask, exit, R, E).
 * Phase 2 (NTHREADS workers): tasks pulled from an atomic queue; each
 *   worker runs the sequential arc-DFS with its own memo hash.
 *
 * Build: gcc -O3 -march=native -pthread -DNSYM=6 -o prove_par prove_par.c
 * Run:   ./prove_par BUDGET [THREADS] [DEPTH]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <signal.h>
#include <time.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>

#ifndef NSYM
#define NSYM 6
#endif
#if NSYM == 4
#define NV 24
#define NCYC 6
#define NLOOPS 8
#elif NSYM == 5
#define NV 120
#define NCYC 24
#define NLOOPS 30
#elif NSYM == 6
#define NV 720
#define NCYC 120
#define NLOOPS 144
#else
#error "unsupported NSYM"
#endif

#define WORDS ((NV + 63) / 64)
#define ZWORDS ((NLOOPS + 63) / 64)
typedef unsigned long long u64;
typedef struct { u64 w[WORDS]; } Mask;
typedef struct { u64 w[ZWORDS]; } ZMask;

static int perm_of[NV][NSYM];
static int nxt[NV];
static int cycid[NV];
static int gen2[NV];            /* vertex -> its 2-loop id (as generator) */
static Mask cym[NCYC];
#define MAXOUT (NV - 1)
static int outw[NV][MAXOUT], outt[NV][MAXOUT], outn[NV];
static Mask arcm[NV][NSYM];
static int arce[NV][NSYM];

static inline void mset(Mask *m, int b) { m->w[b >> 6] |= 1ULL << (b & 63); }
static inline int mget(const Mask *m, int b) { return (m->w[b >> 6] >> (b & 63)) & 1; }
static inline int minter(const Mask *a, const Mask *b) {
    for (int i = 0; i < WORDS; i++) if (a->w[i] & b->w[i]) return 1;
    return 0;
}
static inline int mcovers(const Mask *a, const Mask *b) {
    for (int i = 0; i < WORDS; i++) if ((a->w[i] & b->w[i]) != b->w[i]) return 0;
    return 1;
}
static inline void mor(Mask *a, const Mask *b) {
    for (int i = 0; i < WORDS; i++) a->w[i] |= b->w[i];
}
static inline int mfull(const Mask *a) {
    for (int i = 0; i < WORDS - 1; i++) if (a->w[i] != ~0ULL) return 0;
    int rem = NV & 63;
    u64 last = rem ? ((1ULL << rem) - 1) : ~0ULL;
    return a->w[WORDS - 1] == last;
}

static int weight_of(const int *u, const int *v) {
    for (int k = NSYM - 1; k > 0; k--) {
        int ok = 1;
        for (int t = 0; t < k; t++)
            if (u[NSYM - k + t] != v[t]) { ok = 0; break; }
        if (ok) return NSYM - k;
    }
    return NSYM;
}
static long long fact(int x){ long long f = 1; for (int i = 2; i <= x; i++) f *= i; return f; }
static void gen_perms(void) {
    for (int idx = 0; idx < NV; idx++) {
        int avail[NSYM], na = NSYM, x = idx;
        for (int s = 0; s < NSYM; s++) avail[s] = s + 1;
        for (int pos = 0; pos < NSYM; pos++) {
            long long f = fact(NSYM - 1 - pos);
            int q = x / f; x %= (int)f;
            perm_of[idx][pos] = avail[q];
            memmove(avail + q, avail + q + 1, (na - q - 1) * sizeof(int));
            na--;
        }
    }
}
static int idx_of(const int *p) {
    int avail[NSYM], na = NSYM, rank = 0;
    for (int s = 0; s < NSYM; s++) avail[s] = s + 1;
    for (int pos = 0; pos < NSYM; pos++) {
        int q = 0; while (avail[q] != p[pos]) q++;
        rank += q * fact(NSYM - 1 - pos);
        memmove(avail + q, avail + q + 1, (na - q - 1) * sizeof(int));
        na--;
    }
    return rank;
}

/* build gen2[v]: id of the 2-loop generated by v (HPV walk).  By Prop 1 a
 * 2-loop is generated by the NSYM-1 rotations of v that fix the last entry,
 * so the canonical key is the min rank over those rotations. */
static void build_gen2(void) {
    static int loopkey[NV];
    for (int i = 0; i < NV; i++) loopkey[i] = -1;
    int nloops = 0;
    for (int i = 0; i < NV; i++) {
        int key = i;
        for (int k = 1; k < NSYM - 1; k++) {
            int r[NSYM];
            for (int t = 0; t < NSYM - 1 - k; t++) r[t] = perm_of[i][k + t];
            for (int t = 0; t < k; t++) r[NSYM - 1 - k + t] = perm_of[i][t];
            r[NSYM - 1] = perm_of[i][NSYM - 1];
            int j = idx_of(r);
            if (j < key) key = j;
        }
        if (loopkey[key] < 0) loopkey[key] = nloops++;
        gen2[i] = loopkey[key];
    }
    if (nloops != NLOOPS) {
        fprintf(stderr, "build_gen2: got %d loops, expected %d\n",
                nloops, NLOOPS);
        exit(1);
    }
}

static inline void zset(ZMask *m, int b) { m->w[b >> 6] |= 1ULL << (b & 63); }
static inline int zget(const ZMask *m, int b) { return (m->w[b >> 6] >> (b & 63)) & 1; }

/* ---------- per-thread memo (sized at runtime to fit memory budget) ----- */
#define MAXPROBE 256
typedef struct { Mask m; ZMask z; int e; short re; } HEnt;
static u64 hsize, hmask;
static inline u64 hmix(u64 x){ x^=x>>33; x*=0xff51afd7ed558ccdULL; x^=x>>33; x*=0xc4ceb9fe1a85ec53ULL; x^=x>>33; return x; }

static u64 mem_total_bytes(void) {
    FILE *f = fopen("/proc/meminfo", "r");
    u64 kb = 64ULL << 30;
    if (f) {
        char line[256];
        while (fgets(line, sizeof line, f))
            if (sscanf(line, "MemTotal: %llu kB", &kb) == 1) break;
        fclose(f);
    }
    return kb << 10;
}
static u64 mem_available_bytes(void) {
    FILE *f = fopen("/proc/meminfo", "r");
    u64 kb = 0;
    if (f) {
        char line[256];
        while (fgets(line, sizeof line, f))
            if (sscanf(line, "MemAvailable: %llu kB", &kb) == 1) break;
        fclose(f);
    }
    return kb ? (kb << 10) : mem_total_bytes();
}

static int budget;
static _Atomic long long nodes_total = 0;
static _Atomic int solutions = 0;
static _Atomic int tasks_done = 0;
static double t0;
static double now(void){ struct timespec ts; clock_gettime(CLOCK_MONOTONIC, &ts); return ts.tv_sec + ts.tv_nsec/1e9; }

typedef struct { Mask mask; ZMask z; int e, R, E, more, v; } Task;
static Task *tasks;
static long long ntasks = 0, tasks_cap = 0;
static _Atomic long long task_head = 0;

/* ---------- checkpoint / resume ---------- */
#define CKPT_MAGIC "SPCK0002"
static int gen_depth;
static long long task_limit;
static int gen_abort = 0;
static unsigned char *done_map;        /* done_map[t] = 1 when task t finished */
static volatile sig_atomic_t stop_flag = 0;
static const char *ckpt_path = NULL;
static void on_signal(int sig) { (void)sig; stop_flag = 1; }

static int save_ckpt(void) {
    /* tasks are immutable after generation: only hdr + done_map change.
     * open r+b (no truncate) so the mmap'd task region stays valid. */
    FILE *f = fopen(ckpt_path, "r+b");
    if (!f) return -1;
    char magic[8] = CKPT_MAGIC;
    long long hdr[8] = { NSYM, NV, NCYC, budget, gen_depth, ntasks,
                         (long long)tasks_done, (long long)nodes_total };
    fwrite(magic, 1, 8, f);
    fwrite(hdr, sizeof(long long), 8, f);
    fwrite(&solutions, sizeof(int), 1, f);
    fseek(f, 8 + 64 + 4 + (long long)ntasks * (long long)sizeof(Task),
          SEEK_SET);
    fwrite(done_map, 1, ntasks, f);
    fclose(f);
    return 0;
}

static int load_ckpt(void) {
    FILE *f = fopen(ckpt_path, "rb");
    if (!f) return -1;
    char magic[8];
    long long hdr[8];
    if (fread(magic, 1, 8, f) != 8 || memcmp(magic, CKPT_MAGIC, 8)) {
        fclose(f);
        return -1;
    }
    if (fread(hdr, sizeof(long long), 8, f) != 8) { fclose(f); return -1; }
    if (hdr[0] != NSYM || hdr[1] != NV || hdr[3] != budget) {
        fprintf(stderr, "[ckpt] parameter mismatch (file: n=%lld NV=%lld "
                "budget=%lld)\n", hdr[0], hdr[1], hdr[3]);
        fclose(f);
        return -1;
    }
    gen_depth = (int)hdr[4];
    ntasks = hdr[5];
    long long prev_done = hdr[6], prev_nodes = hdr[7];
    if (fread(&solutions, sizeof(int), 1, f) != 1) { fclose(f); return -1; }
    /* mmap task region read-only (page cache spills to disk) */
    {
        int fd = open(ckpt_path, O_RDONLY);
        if (fd < 0) { perror("open ckpt"); exit(1); }
        size_t tb = (size_t)ntasks * sizeof(Task);
        size_t hs = 8 + 64 + 4;
        void *mp = mmap(NULL, tb + hs, PROT_READ, MAP_SHARED, fd, 0);
        if (mp == MAP_FAILED) { perror("mmap"); exit(1); }
        tasks = (Task *)((char *)mp + hs);
        close(fd);
    }
    done_map = malloc(ntasks);
    if (!done_map) { fprintf(stderr, "[ckpt] alloc failed\n"); exit(1); }
    if (fread(done_map, 1, ntasks, f) != (size_t)ntasks) {
        fprintf(stderr, "[ckpt] truncated file\n"); exit(1);
    }
    fclose(f);
    tasks_done = prev_done;
    nodes_total = prev_nodes;
    printf("[ckpt] resumed: %lld tasks, %lld already done, %lld nodes so far\n",
           ntasks, prev_done, prev_nodes), fflush(stdout);
    return 0;
}

/* ---------- task generation (single-threaded DFS to arc-depth DEPTH) --- */
#define GEN_BUF_MAX (1 << 18)
static FILE *gen_file;
static Task *gen_buf;
static long gen_buf_len;
static void gen_flush(void) {
    if (gen_buf_len) {
        if (fwrite(gen_buf, sizeof(Task), gen_buf_len, gen_file)
            != (size_t)gen_buf_len) {
            fprintf(stderr, "gen stream write failed (disk full?)\n");
            exit(1);
        }
        gen_buf_len = 0;
    }
}
static void gen_dfs_cov(int e, Mask *mask, ZMask *z, int v, int R, int E,
                        int depthleft, int more) {
    if (gen_abort) return;
    if (depthleft == 0 || mfull(mask)) {
        if (ntasks >= task_limit) { gen_abort = 1; return; }
        gen_buf[gen_buf_len++] = (Task){ *mask, *z, e, R, E, more, v };
        ntasks++;
        if (gen_buf_len == GEN_BUF_MAX) gen_flush();
        return;
    }
    if (R + more + E > budget) return;
    if (v > budget - NCYC + 1) return;
    /* E-lookahead: the next jump must pay the excess of the cheapest
       unvisited target (out-edges sorted by weight) */
    int minex = NSYM;
    for (int t = 0; t < outn[e]; t++)
        if (!mget(mask, outt[e][t])) { minex = outw[e][t] - 2; break; }
    if (R + more + E + minex > budget) return;
    for (int t = 0; t < outn[e]; t++) {
        int w = outw[e][t], s = outt[e][t];
        int ne = E + (w - 2);
        if (R + more + ne > budget) break;
        if (mget(mask, s)) continue;
        int sc = cycid[s];          /* arc lives entirely in cycle sc */
        ZMask z2 = *z;
        int v2 = v;
        if (!zget(&z2, gen2[s])) { zset(&z2, gen2[s]); v2++; }
        if (v2 > budget - NCYC + 1) continue;
        for (int L = 0; L < NSYM; L++) {
            if (minter(&arcm[s][L], mask)) break;
            Mask nm = *mask;
            mor(&nm, &arcm[s][L]);
            int more2 = more - (mcovers(&nm, &cym[sc]) ? 1 : 0);
            gen_dfs_cov(arce[s][L], &nm, &z2, v2, R + 1, ne,
                        depthleft - 1, more2);
        }
    }
}
static void gen_dfs(int e, Mask *mask, int R, int E, int depthleft) {
    int more = 0;
    for (int c = 0; c < NCYC; c++)
        if (!mcovers(mask, &cym[c])) more++;
    ZMask z0;
    for (int i = 0; i < ZWORDS; i++) z0.w[i] = 0;
    gen_dfs_cov(e, mask, &z0, 0, R, E, depthleft, more);
}

/* ---------- worker DFS (incremental coverage count) ---------- */
static void worker_dfs(HEnt *htab, int e, Mask *mask, ZMask *z, int v,
                       int R, int E, int more, long long *lnodes) {
    (*lnodes)++;
    if (((*lnodes) & 0xFFFFF) == 0 && stop_flag) return;
    if (mfull(mask)) {
        solutions++;
        printf("[prove] SOLUTION cost=%d (R=%d, E=%d)\n",
               NV + R - 2 + E, R, E), fflush(stdout);
        return;
    }
    int re = R * 100 + E;
    {
        u64 h = (u64)e * 0x9e3779b97f4a7c15ULL;
        for (int i = 0; i < WORDS; i++) h ^= hmix(mask->w[i] + 0x9e3779b97f4a7c15ULL * i);
        for (int i = 0; i < ZWORDS; i++) h ^= hmix(z->w[i] + 0x85ebca6b * (i + 7));
        for (u64 k = hmix(h) & hmask, probe = 0; probe < MAXPROBE;
             k = (k + 1) & hmask, probe++) {
            HEnt *p = &htab[k];
            if (p->re == -1) { p->m = *mask; p->z = *z; p->e = e; p->re = (short)re; goto miss; }
            if (p->e == e && !memcmp(&p->m, mask, sizeof(Mask))
                && !memcmp(&p->z, z, sizeof(ZMask))) {
                if (p->re <= re) return;
                p->re = (short)re;
                goto miss;
            }
        }
    }
miss:;
    if (R + more + E > budget) return;
    if (v > budget - NCYC + 1) return;
    int minex = NSYM;
    for (int t = 0; t < outn[e]; t++)
        if (!mget(mask, outt[e][t])) { minex = outw[e][t] - 2; break; }
    if (R + more + E + minex > budget) return;
    for (int t = 0; t < outn[e]; t++) {
        int w = outw[e][t], s = outt[e][t];
        int ne = E + (w - 2);
        if (R + more + ne > budget) break;
        if (mget(mask, s)) continue;
        int sc = cycid[s];
        ZMask z2 = *z;
        int v2 = v;
        if (!zget(&z2, gen2[s])) { zset(&z2, gen2[s]); v2++; }
        if (v2 > budget - NCYC + 1) continue;
        for (int L = 0; L < NSYM; L++) {
            if (minter(&arcm[s][L], mask)) break;
            Mask nm = *mask;
            mor(&nm, &arcm[s][L]);
            int more2 = more - (mcovers(&nm, &cym[sc]) ? 1 : 0);
            worker_dfs(htab, arce[s][L], &nm, &z2, v2, R + 1, ne, more2,
                       lnodes);
        }
    }
}

static void *worker(void *arg) {
    HEnt *htab = malloc(sizeof(HEnt) * hsize);
    if (!htab) { fprintf(stderr, "worker htab alloc failed\n"); exit(1); }
    for (u64 k = 0; k < hsize; k++) htab[k].re = -1;
    long long lnodes = 0;
    for (;;) {
        if (stop_flag) break;
        long long t = task_head++;
        if (t >= ntasks) break;
        if (done_map[t]) { ++tasks_done; continue; }
        Task *tk = &tasks[t];
        Mask m = tk->mask;
        worker_dfs(htab, tk->e, &m, &tk->z, tk->v, tk->R, tk->E,
                   tk->more, &lnodes);
        done_map[t] = 1;
        int done = ++tasks_done;
        if (done % 64 == 0) {
            long long nt = nodes_total += 0; /* read */
            printf("[prove] tasks %lld/%lld (%.1f%%) elapsed=%.1fs sol=%d\n",
                   (long long)done, ntasks, 100.0 * done / ntasks,
                   now() - t0, (int)solutions), fflush(stdout);
        }
    }
    nodes_total += lnodes;
    free(htab);
    return NULL;
}

int main(int argc, char **argv) {
    if (argc < 2) { fprintf(stderr, "usage: %s BUDGET [THREADS] [DEPTH]\n", argv[0]); return 2; }
    budget = atoi(argv[1]);
    int nthreads = argc > 2 ? atoi(argv[2]) : 16;
    gen_depth = argc > 3 ? atoi(argv[3]) : 10;
    gen_perms();
    build_gen2();
    {
        char g2path[64];
        snprintf(g2path, sizeof g2path, "gen2_n%d.bin", NSYM);
        FILE *g2 = fopen(g2path, "wb");
        if (g2) { fwrite(gen2, sizeof(int), NV, g2); fclose(g2); }
    }
    for (int i = 0; i < NV; i++) {
        int r[NSYM];
        for (int k = 0; k < NSYM - 1; k++) r[k] = perm_of[i][k + 1];
        r[NSYM - 1] = perm_of[i][0];
        nxt[i] = idx_of(r);
    }
    int seen[NV] = {0}, nc = 0;
    for (int i = 0; i < NV; i++) {
        if (seen[i]) continue;
        Mask m; memset(&m, 0, sizeof m);
        int j = i;
        while (!seen[j]) { seen[j] = 1; cycid[j] = nc; mset(&m, j); j = nxt[j]; }
        cym[nc++] = m;
    }
    for (int i = 0; i < NV; i++)
        for (int w = 2; w <= NSYM; w++)
            for (int j = 0; j < NV; j++)
                if (weight_of(perm_of[i], perm_of[j]) == w) {
                    outw[i][outn[i]] = w; outt[i][outn[i]] = j; outn[i]++;
                }
    for (int s = 0; s < NV; s++) {
        Mask m; memset(&m, 0, sizeof m);
        int j = s;
        for (int L = 0; L < NSYM; L++) {
            mset(&m, j);
            arcm[s][L] = m; arce[s][L] = j;
            j = nxt[j];
        }
    }
    /* ---- memory budgeting: stay under 80% of AVAILABLE RAM ---- */
    u64 memtotal = mem_available_bytes();
    u64 memcap = memtotal / 100 * 80;
    /* per-thread hash: total across threads <= 30% of available RAM */
    u64 htab_bytes = memtotal / 100 * 30 / (u64)nthreads;
    int hbits = 20;
    while (hbits < 30 && (1ULL << (hbits + 1)) * sizeof(HEnt) <= htab_bytes)
        hbits++;
    hsize = 1ULL << hbits;
    hmask = hsize - 1;
    /* task array cap: remaining headroom after hash tables and 8GB slack */
    u64 used = (u64)nthreads * hsize * sizeof(HEnt);
    u64 task_cap = 1 << 16;
    if (used + (8ULL << 30) < memcap) {
        u64 avail = memcap - used - (8ULL << 30);
        task_cap = avail / sizeof(Task);
    }
    task_cap = 1ULL << 31;   /* effectively unbounded: disk is the limit */
    printf("[prove] memory: avail=%.1fGB cap80=%.1fGB htab=%.1fGB/thread "
           "(2^%d entries x %d threads) taskcap=disk-bounded\n",
           memtotal / 1e9, memcap / 1e9,
           hsize * sizeof(HEnt) / 1e9, hbits, nthreads), fflush(stdout);

    ckpt_path = argc > 4 ? argv[4] : NULL;
    int resumed = 0;
    if (ckpt_path && load_ckpt() == 0) {
        resumed = 1;
    } else {
        if (!ckpt_path) {
            fprintf(stderr, "[prove] FATAL: generation requires a ckpt path "
                    "(streaming to disk)\n");
            return 1;
        }
        printf("[prove] parallel prover n=%d: budget R+E<=%d, %d threads, "
               "split depth %d (streaming to %s)\n", NSYM, budget, nthreads,
               gen_depth, ckpt_path), fflush(stdout);
        const off_t hdr_size = 8 + 64 + 4;
        task_limit = (1LL << 62);   /* disk is the only limit */
        gen_buf = malloc(GEN_BUF_MAX * sizeof(Task));
        if (!gen_buf) { fprintf(stderr, "gen_buf alloc failed\n"); return 1; }
        for (;;) {
            t0 = now();
            gen_file = fopen(ckpt_path, "wb");
            if (!gen_file) { fprintf(stderr, "cannot open %s\n", ckpt_path);
                return 1; }
            char zeros[8 + 64 + 4];
            memset(zeros, 0, sizeof zeros);
            fwrite(zeros, 1, sizeof zeros, gen_file);   /* hdr placeholder */
            ntasks = 0;
            gen_buf_len = 0;
            gen_abort = 0;
            for (int L = 0; L < NSYM; L++)
                gen_dfs(arce[0][L], &arcm[0][L], 1, 0, gen_depth);
            gen_flush();
            fclose(gen_file);
            if (!gen_abort) break;
            gen_depth--;
            printf("[prove] task overflow (>1e31??), retrying depth %d\n",
                   gen_depth), fflush(stdout);
            if (gen_depth <= 0) {
                fprintf(stderr, "[prove] FATAL: cannot generate\n");
                return 1;
            }
        }
        printf("[prove] generated %lld tasks in %.1fs\n", ntasks, now() - t0),
            fflush(stdout);
        free(gen_buf);
        /* finalize ckpt: done_map zeros + real header */
        {
            FILE *f = fopen(ckpt_path, "r+b");
            fseek(f, 0, SEEK_END);
            char *zblock = calloc(1 << 20, 1);
            long long rem = ntasks;
            while (rem > 0) {
                long long c = rem > (1 << 20) ? (1 << 20) : rem;
                fwrite(zblock, 1, c, f);
                rem -= c;
            }
            free(zblock);
            fseek(f, 0, SEEK_SET);
            char magic[8] = CKPT_MAGIC;
            long long hdr[8] = { NSYM, NV, NCYC, budget, gen_depth, ntasks,
                                 0, 0 };
            int sol0 = 0;
            fwrite(magic, 1, 8, f);
            fwrite(hdr, sizeof(long long), 8, f);
            fwrite(&sol0, sizeof(int), 1, f);
            fclose(f);
            printf("[ckpt] frontier streamed: %lld tasks (%.1fGB)\n",
                   ntasks, (ntasks * (sizeof(Task) + 1)) / 1e9), fflush(stdout);
        }
        /* mmap the task region for the worker phase */
        {
            int fd = open(ckpt_path, O_RDONLY);
            if (fd < 0) { perror("open ckpt"); return 1; }
            size_t tb = (size_t)ntasks * sizeof(Task);
            void *mp = mmap(NULL, tb + hdr_size, PROT_READ, MAP_SHARED,
                            fd, 0);
            if (mp == MAP_FAILED) { perror("mmap"); return 1; }
            tasks = (Task *)((char *)mp + hdr_size);
            close(fd);
            printf("[ckpt] task region mmap'd read-only (%.1fGB)\n",
                   tb / 1e9), fflush(stdout);
        }
        done_map = calloc(ntasks, 1);
        if (!done_map) { fprintf(stderr, "done_map alloc failed\n"); return 1; }
    }
    (void)resumed;
    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);
    t0 = now();

    pthread_t *th = malloc(nthreads * sizeof(pthread_t));
    for (int i = 0; i < nthreads; i++) pthread_create(&th[i], NULL, worker, NULL);
    /* watcher: check every 2s, checkpoint every 120s */
    double last_ck = now();
    while ((long long)tasks_done < ntasks && !stop_flag) {
        struct timespec ts = { 2, 0 };
        nanosleep(&ts, NULL);
        if (ckpt_path && now() - last_ck >= 120.0) {
            last_ck = now();
            if (save_ckpt() == 0)
                printf("[ckpt] periodic checkpoint: %lld/%lld done\n",
                       (long long)tasks_done, ntasks), fflush(stdout);
        }
    }
    stop_flag = 1;   /* tell workers to wind down (no-op if already done) */
    for (int i = 0; i < nthreads; i++) pthread_join(th[i], NULL);

    if ((long long)tasks_done < ntasks) {
        if (ckpt_path && save_ckpt() == 0)
            printf("[ckpt] INTERRUPTED: progress saved (%lld/%lld tasks). "
                   "Resume with: %s %d %d %d %s\n",
                   (long long)tasks_done, ntasks, argv[0], budget, nthreads,
                   gen_depth, ckpt_path), fflush(stdout);
        printf("[prove] interrupted — NOT certified (partial search)\n"),
            fflush(stdout);
        return 3;
    }
    printf("[prove] DONE nodes=%lld tasks=%lld sol=%d elapsed=%.1fs\n",
           (long long)nodes_total, ntasks, (int)solutions, now() - t0),
        fflush(stdout);
    if (!solutions)
        printf("[prove] CERTIFIED: no path cost <= %d => min cost >= %d"
               " => s(%d) >= %d\n", NV + budget - 2, NV + budget - 1,
               NSYM, NV + budget - 1 + NSYM), fflush(stdout);
    return 0;
}
