/* splitfree6b.c -- splitfree6.c with the FULL-LOOP bound.
 *
 * Question unchanged: is there a SPLIT-FREE 6-symbol superpermutation of the
 * minimal length 872?  length = 844 + E, so a champion needs E <= 28.
 *
 * What is new is the pruning.  splitfree6.c bounds the remaining cost by
 * ceil(rem / 5) -- "every future block covers at most 5 classes".  That is
 * weak, because a block of length 5 is not just any 5 classes: a run is
 * delta-consecutive inside one 2-loop, so a length-5 run is an ENTIRE loop,
 * and it can only happen if all 5 of that loop's classes are still uncovered.
 *
 * Track U = #{loops with all 5 classes uncovered}.  Any future length-5 run
 * consumes one of them, so with x5 such runs and every other block covering
 * at most 4 classes,
 *
 *      need <= 5*x5 + 4*(blocks - x5),   x5 <= min(U, floor(need/5))
 *   => blocks >= ceil((need - min(U, floor(need/5))) / 4).
 *
 * At the root U is large and this agrees with ceil(need/5).  Deep in the
 * search U collapses -- covering half the classes leaves only a few percent
 * of loops intact -- and the bound pulls ahead, which is exactly where the
 * old search drowned.
 *
 * There are 144 two-loops at n = 6 (each of size 30, each permutation in 6 of
 * them, each with 5 generators, one per class).  They are the cycles of
 * next(p) = delta(sigma^5(p)) acting on the 720 permutations.
 *
 * SHARDING.  The tree is wildly unbalanced -- essentially all of it hangs off
 * the delta move and the six weight-3 moves -- so splitting on the first move
 * is useless.  Instead every process walks the identical tree down to
 * SHARD_DEPTH and then keeps only every NSHARDS-th node at that depth.  The
 * prefix above the cut is explored redundantly (cheap) and the work below it
 * is spread evenly.  The counter is deterministic, so the shards partition the
 * search exactly.
 *
 * SPLITTING BY (B, Y).  E = (B-1) + Y, so the single constraint E <= 28 lets
 * blocks and excess weight TRADE against each other.  Fixing B kills the
 * trade and gives two separate constraints,
 *
 *      #blocks + (future blocks) <= B        and     Y <= 29 - B,
 *
 * which together are strictly stronger than E <= 28 alone.  Since B >= 24
 * always, running B = 24..29 with Y <= 29-B covers every champion candidate.
 * Large B is the case where Y collapses to 0 and every jump must have weight
 * exactly 3 -- and an arc end has only six weight-3 targets.
 *
 * Build: gcc -O3 -march=native -o code/sf6b code/splitfree6b.c
 * Run:   ./code/sf6b <budget> [nodecap] [maxw] [nshards] [myshard] [depth]
 *                    [Bexact] [Ymax]
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define N 6
#define NP 720            /* permutations              */
#define NC 120            /* rotation classes = (n-1)! */
#define NL 144            /* two-loops                 */

static unsigned char P[NP][N];
static int idx_of(const unsigned char *p)
{
    for (int i = 0; i < NP; i++)
        if (!memcmp(P[i], p, N)) return i;
    return -1;
}

static int cls[NP];
static int aend[NP];
static int dtar[NP];
static int wt[NP][NP];
static int *order[NP];

static int lid[NP];               /* loop generated by this arc start */
static int cls_loops[NC][N];      /* the 6 loops meeting a class      */
static int lcnt[NL];              /* covered classes of each loop     */
static int U;                     /* loops with lcnt == 0             */

static void gen_perms(void)
{
    unsigned char a[N];
    for (int i = 0; i < N; i++) a[i] = i + 1;
    int cnt = 0;
    while (1) {
        memcpy(P[cnt++], a, N);
        int i = N - 2;
        while (i >= 0 && a[i] >= a[i + 1]) i--;
        if (i < 0) break;
        int j = N - 1;
        while (a[j] <= a[i]) j--;
        unsigned char t = a[i]; a[i] = a[j]; a[j] = t;
        for (int l = i + 1, r = N - 1; l < r; l++, r--) { t = a[l]; a[l] = a[r]; a[r] = t; }
    }
    if (cnt != NP) { fprintf(stderr, "perm count %d\n", cnt); exit(1); }
}

static void rot(const unsigned char *u, unsigned char *w)
{
    for (int i = 0; i < N - 1; i++) w[i] = u[i + 1];
    w[N - 1] = u[0];
}

static int weight(const unsigned char *u, const unsigned char *w)
{
    for (int k = 1; k <= N; k++) {
        int ok = 1;
        for (int i = 0; i < N - k; i++)
            if (u[k + i] != w[i]) { ok = 0; break; }
        if (ok) return k;
    }
    return N;
}

static void build(void)
{
    gen_perms();

    for (int i = 0; i < NP; i++) cls[i] = -1;
    int nc = 0;
    for (int i = 0; i < NP; i++) {
        if (cls[i] >= 0) continue;
        unsigned char x[N];
        memcpy(x, P[i], N);
        for (int k = 0; k < N; k++) {
            cls[idx_of(x)] = nc;
            unsigned char y[N]; rot(x, y); memcpy(x, y, N);
        }
        nc++;
    }
    if (nc != NC) { fprintf(stderr, "classes %d\n", nc); exit(1); }

    for (int i = 0; i < NP; i++) {
        unsigned char x[N], y[N];
        memcpy(x, P[i], N);
        for (int k = 0; k < N - 1; k++) { rot(x, y); memcpy(x, y, N); }
        aend[i] = idx_of(x);
    }
    for (int e = 0; e < NP; e++) {
        unsigned char d[N];
        for (int i = 0; i < N - 2; i++) d[i] = P[e][i + 2];
        d[N - 2] = P[e][1];
        d[N - 1] = P[e][0];
        dtar[e] = idx_of(d);
    }

    for (int i = 0; i < NP; i++)
        for (int j = 0; j < NP; j++)
            wt[i][j] = weight(P[i], P[j]);

    for (int e = 0; e < NP; e++) {
        order[e] = malloc(sizeof(int) * NP);
        int k = 0;
        for (int w = 1; w <= N; w++)
            for (int q = 0; q < NP; q++)
                if (wt[e][q] == w) order[e][k++] = q;
    }

    /* two-loops = cycles of next(p) = delta(sigma^5(p)) = dtar[aend[p]] */
    for (int i = 0; i < NP; i++) lid[i] = -1;
    int nl = 0;
    for (int i = 0; i < NP; i++) {
        if (lid[i] >= 0) continue;
        int x = i, k = 0;
        do { lid[x] = nl; k++; x = dtar[aend[x]]; } while (x != i);
        if (k != N - 1) { fprintf(stderr, "loop len %d\n", k); exit(1); }
        nl++;
    }
    if (nl != NL) { fprintf(stderr, "loops %d\n", nl); exit(1); }

    int fill[NC];
    memset(fill, 0, sizeof fill);
    for (int p = 0; p < NP; p++)
        cls_loops[cls[p]][fill[cls[p]]++] = lid[p];
    for (int c = 0; c < NC; c++)
        if (fill[c] != N) { fprintf(stderr, "class %d in %d loops\n", c, fill[c]); exit(1); }
}

/* ---- search ------------------------------------------------------------- */
static int budget, covered_cnt, found, maxw;
static unsigned char covered[NC];
static long long nodes, node_cap;
static int trail[NC];

static void cover_class(int c)
{
    covered[c] = 1; covered_cnt++;
    for (int t = 0; t < N; t++)
        if (lcnt[cls_loops[c][t]]++ == 0) U--;
}

static void uncover_class(int c)
{
    for (int t = 0; t < N; t++)
        if (--lcnt[cls_loops[c][t]] == 0) U++;
    covered_cnt--; covered[c] = 0;
}

/* fewest further blocks needed for `need` classes, given u intact loops */
static int lo_blocks_u(int need, int u)
{
    if (need <= 0) return 0;
    int x5 = need / (N - 1);
    if (x5 > u) x5 = u;
    return (need - x5 + N - 3) / (N - 2);      /* ceil((need - x5) / 4) */
}

static int lo_blocks(int need) { return lo_blocks_u(need, U); }

static int nshards = 1, myshard = 0, shard_depth = 12;
static int Bexact = 0, Ymax = 0;       /* Bexact = 0 disables the (B,Y) split */
static long long seq;

static void dfs(int e, int cost, int curlen, int depth, int nblk, int ycost)
{
    if (found || ++nodes > node_cap) return;
    if (covered_cnt == NC) {
        if (!Bexact || nblk == Bexact) { found = 1; return; }
        return;
    }
    if (depth == shard_depth && (seq++ % nshards) != myshard) return;

    int rem = NC - covered_cnt;
    int fut = lo_blocks(rem - ((N - 1) - curlen));
    if (cost + fut > budget) return;
    if (Bexact && nblk + fut > Bexact) return;

    int q = dtar[e];
    if (!covered[cls[q]] && curlen < N - 1) {
        cover_class(cls[q]); trail[depth] = q;
        dfs(aend[q], cost, curlen + 1, depth + 1, nblk, ycost);
        uncover_class(cls[q]);
        if (found) return;
    }
    /* Target-independent floor on the post-move block bound, hoisted out of
     * the loop.  Without it the loop scans all 720 targets at every node,
     * because cost + w - 2 alone never exceeds the budget while cost is small
     * -- and that constant factor, not the node count, is what made E <= 27
     * look unreachable.
     *
     * lo_blocks_u is DECREASING in u, and covering a class can only shrink U,
     * so U_after <= U and lo_blocks_u(need, U) <= lo_blocks_u(need, U_after).
     * Evaluating at U therefore gives a valid lower bound for every target r.
     * (Evaluating at U-6 gives an UPPER bound instead; that over-prunes, and
     * the E <= 29 gate caught it immediately -- the classical 873 vanished.) */
    int f2min = lo_blocks_u(rem - 1 - (N - 2), U);
    int wcap = budget - cost + 2 - f2min;
    if (wcap > maxw) wcap = maxw;

    for (int t = 0; t < NP; t++) {
        int r = order[e][t];
        int w = wt[e][r];
        if (w < 3) continue;
        if (w > wcap) break;                    /* order[] is sorted by w */
        int c = cost + w - 2;
        int yc = ycost + w - 3;
        if (Bexact && yc > Ymax) break;
        if (covered[cls[r]]) continue;
        /* the new block starts at r, so bound against the POST-move state */
        cover_class(cls[r]);
        int f2 = lo_blocks(rem - 1 - (N - 2));
        if (c + f2 <= budget && (!Bexact || nblk + 1 + f2 <= Bexact)) {
            trail[depth] = r;
            dfs(aend[r], c, 1, depth + 1, nblk + 1, yc);
        }
        uncover_class(cls[r]);
        if (found) return;
    }
}

int main(int argc, char **argv)
{
    budget   = (argc > 1) ? atoi(argv[1]) : 28;
    node_cap = (argc > 2) ? atoll(argv[2]) : 100000000000LL;
    maxw     = (argc > 3) ? atoi(argv[3]) : N;
    nshards  = (argc > 4) ? atoi(argv[4]) : 1;
    myshard  = (argc > 5) ? atoi(argv[5]) : 0;
    shard_depth = (argc > 6) ? atoi(argv[6]) : 12;
    Bexact   = (argc > 7) ? atoi(argv[7]) : 0;
    Ymax     = (argc > 8) ? atoi(argv[8]) : (Bexact ? budget + 1 - Bexact : 0);
    build();

    printf("n = 6 split-free, full-loop bound: %d classes, %d two-loops\n",
           NC, NL);
    printf("budget E <= %d (length <= %d), maxw %d, shard %d/%d at depth %d\n",
           budget, 844 + budget, maxw, myshard, nshards, shard_depth);
    if (Bexact) printf("case B = %d exactly, Y <= %d\n", Bexact, Ymax);

    memset(covered, 0, sizeof covered);
    memset(lcnt, 0, sizeof lcnt);
    U = NL;
    cover_class(cls[0]); trail[0] = 0;         /* WLOG the first arc = identity */
    nodes = 0; found = 0; seq = 0;
    dfs(aend[0], 0, 1, 1, 1, 0);

    printf("nodes = %lld%s\n", nodes,
           nodes > node_cap ? "  (CAP HIT -- inconclusive)" : "");
    if (found) {
        printf("FEASIBLE: a split-free walk with E <= %d exists (length <= %d)\n",
               budget, 844 + budget);
        printf("first arcs:");
        for (int i = 0; i < 10; i++) {
            printf(" ");
            for (int k = 0; k < N; k++) printf("%d", P[trail[i]][k]);
        }
        printf(" ...\n");
    } else if (nodes <= node_cap) {
        printf("IMPOSSIBLE on this shard: no split-free walk with E <= %d\n",
               budget);
    }
    return 0;
}
